#!/bin/bash

linter="$1"
image="sendwithus/linter-$linter:latest"

docker build -t $image $linter || exit $?

echo
read -p "Push to Docker Hub? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    docker push $image
fi
